"""
inter_rater_analysis.py
=======================
Computes inter-rater reliability for the AI Misuse Evaluator dissertation.

HOW TO USE:
1. Collect CSV responses from 2+ raters (generated by inter_rater_scoring_sheet.html).
2. Save each rater's CSV as data/rater_1.csv, data/rater_2.csv, etc.
3. Also save YOUR OWN scores (from usecases.csv) as data/rater_0.csv.
4. Run:  python src/inter_rater_analysis.py
5. Copy the output into your dissertation Chapter 3.5 or Chapter 4.

CSV FORMAT (what each rater sends you):
    use_case_name,ethical_risk_score,transparency_score
    Medical_Triage_Assistant,1,4
    Deepfake_Voice_Tool,5,1
    ...

OUTPUT:
  - Cohen's Kappa for each pair of raters (ethical risk + transparency)
  - Krippendorff's Alpha across all raters (ordinal)
  - Percentage exact agreement
  - Mean absolute disagreement per use case
  - Summary table for dissertation
"""

import csv
import math
import os
from collections import defaultdict
from itertools import combinations

import numpy as np
import pandas as pd

# ── The 12 use cases that appear on the scoring sheet ────────────────────────
RATER_CASES = [
    "Medical_Triage_Assistant",
    "Deepfake_Voice_Tool",
    "Earthquake_Early_Warning",
    "Loan_Approval_Model",
    "AI_Art_Generator",
    "Voter_Suppression_AI",
    "Code_Assistant",
    "Predictive_Policing_Tool",
    "Accessibility_Captioning",
    "Emotion_Analysis_For_HR",
    "Nonconsensual_Deepfake_Generator",
    "Climate_Forecasting_Model",
]

# ── Your own scores for the same 12 cases (from usecases.csv) ────────────────
# Update these if you change your usecases.csv values.
AUTHOR_SCORES = {
    "Medical_Triage_Assistant":          {"ethical_risk_score": 1, "transparency_score": 2},
    "Deepfake_Voice_Tool":               {"ethical_risk_score": 5, "transparency_score": 1},
    "Earthquake_Early_Warning":          {"ethical_risk_score": 1, "transparency_score": 5},
    "Loan_Approval_Model":               {"ethical_risk_score": 4, "transparency_score": 2},
    "AI_Art_Generator":                  {"ethical_risk_score": 3, "transparency_score": 3},
    "Voter_Suppression_AI":              {"ethical_risk_score": 5, "transparency_score": 1},
    "Code_Assistant":                    {"ethical_risk_score": 2, "transparency_score": 3},
    "Predictive_Policing_Tool":          {"ethical_risk_score": 5, "transparency_score": 1},
    "Accessibility_Captioning":          {"ethical_risk_score": 1, "transparency_score": 4},
    "Emotion_Analysis_For_HR":           {"ethical_risk_score": 4, "transparency_score": 1},
    "Nonconsensual_Deepfake_Generator":  {"ethical_risk_score": 5, "transparency_score": 1},
    "Climate_Forecasting_Model":         {"ethical_risk_score": 1, "transparency_score": 4},
}


# ════════════════════════════════════════════════════════════════════════════
# COHEN'S KAPPA (for ordinal data — linear weighted kappa)
# ════════════════════════════════════════════════════════════════════════════

def weighted_cohen_kappa(ratings_a: list[int], ratings_b: list[int],
                         min_val: int = 1, max_val: int = 5) -> float:
    """
    Linear weighted Cohen's Kappa.

    Linear weighting: weight(i,j) = 1 - |i-j| / (max_val - min_val)
    This is more appropriate than unweighted kappa for ordinal scales because
    it treats a disagreement of 1 point as less severe than a disagreement of 4.

    Returns kappa in [-1, 1]:
      > 0.80  almost perfect agreement
      0.61-0.80  substantial agreement
      0.41-0.60  moderate agreement
      0.21-0.40  fair agreement
      < 0.20  slight agreement or worse
    """
    n = len(ratings_a)
    assert len(ratings_b) == n, "Rating lists must have the same length"
    k = max_val - min_val + 1  # number of categories

    # Observed agreement (weighted)
    p_obs = sum(
        1 - abs(a - b) / (max_val - min_val)
        for a, b in zip(ratings_a, ratings_b)
    ) / n

    # Expected agreement (weighted, using marginal distributions)
    freq_a = [ratings_a.count(v) / n for v in range(min_val, max_val + 1)]
    freq_b = [ratings_b.count(v) / n for v in range(min_val, max_val + 1)]

    p_exp = 0.0
    for i, va in enumerate(range(min_val, max_val + 1)):
        for j, vb in enumerate(range(min_val, max_val + 1)):
            weight = 1 - abs(va - vb) / (max_val - min_val)
            p_exp += weight * freq_a[i] * freq_b[j]

    if p_exp >= 1.0:
        return 1.0  # edge case: all ratings are identical

    return (p_obs - p_exp) / (1.0 - p_exp)


def interpret_kappa(kappa: float) -> str:
    if kappa > 0.80: return "almost perfect"
    if kappa > 0.60: return "substantial"
    if kappa > 0.40: return "moderate"
    if kappa > 0.20: return "fair"
    return "slight / poor"


# ════════════════════════════════════════════════════════════════════════════
# KRIPPENDORFF'S ALPHA (for multiple raters, ordinal)
# ════════════════════════════════════════════════════════════════════════════

def krippendorff_alpha_ordinal(data: list[list[float | None]]) -> float:
    """
    Krippendorff's Alpha with ordinal metric (squared differences).

    data: list of rater lists, each of length n_items.
          Use None for missing values.

    Returns alpha in [-1, 1]:
      >= 0.80  good reliability
      >= 0.67  acceptable for tentative conclusions
      < 0.67   unreliable
    """
    # Flatten to list of (rater, item, value) triples, skipping None
    n_items = len(data[0])
    values_per_item = defaultdict(list)
    all_values = []

    for rater_idx, rater_data in enumerate(data):
        for item_idx, val in enumerate(rater_data):
            if val is not None:
                values_per_item[item_idx].append(float(val))
                all_values.append(float(val))

    if len(all_values) < 2:
        return float("nan")

    # Observed disagreement
    D_o = 0.0
    n_pairs = 0
    for item_idx, vals in values_per_item.items():
        if len(vals) < 2:
            continue
        for i in range(len(vals)):
            for j in range(i + 1, len(vals)):
                D_o += (vals[i] - vals[j]) ** 2
                n_pairs += 1

    if n_pairs == 0:
        return float("nan")
    D_o /= n_pairs

    # Expected disagreement (from overall distribution)
    n_total = len(all_values)
    D_e = 0.0
    for i in range(n_total):
        for j in range(i + 1, n_total):
            D_e += (all_values[i] - all_values[j]) ** 2
    D_e /= (n_total * (n_total - 1) / 2)

    if D_e == 0.0:
        return 1.0

    return 1.0 - (D_o / D_e)


# ════════════════════════════════════════════════════════════════════════════
# LOADING AND MAIN ANALYSIS
# ════════════════════════════════════════════════════════════════════════════

def load_rater_csv(path: str) -> dict[str, dict[str, int]]:
    """Load a rater CSV → {use_case_name: {ethical_risk_score: int, transparency_score: int}}"""
    result = {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row["use_case_name"].strip()
            if name not in RATER_CASES:
                continue
            try:
                eth = int(row["ethical_risk_score"])
                tr  = int(row["transparency_score"])
                if 1 <= eth <= 5 and 1 <= tr <= 5:
                    result[name] = {"ethical_risk_score": eth, "transparency_score": tr}
            except (ValueError, KeyError):
                pass  # skip malformed rows
    return result


def run_analysis(rater_files: list[str]) -> str:
    """
    Load rater files + author scores, compute all reliability metrics,
    return a formatted report string.
    """
    # ── Load all raters ──────────────────────────────────────────────────
    raters = {"Author (Hasini)": AUTHOR_SCORES}
    for path in rater_files:
        label = os.path.splitext(os.path.basename(path))[0]  # e.g. "rater_1"
        scores = load_rater_csv(path)
        if scores:
            raters[label] = scores
        else:
            print(f"  ⚠  No valid scores found in {path} — skipping.")

    if len(raters) < 2:
        return "ERROR: Need at least 2 raters (author + 1 external rater)."

    rater_names = list(raters.keys())
    print(f"\nLoaded {len(raters)} raters: {rater_names}")

    # ── Build aligned score lists ────────────────────────────────────────
    # Only use cases present in ALL raters
    common_cases = set(RATER_CASES)
    for rater_data in raters.values():
        common_cases &= set(rater_data.keys())
    common_cases = sorted(common_cases, key=lambda x: RATER_CASES.index(x))

    print(f"Use cases with complete data from all raters: {len(common_cases)}/{len(RATER_CASES)}")

    lines = []
    lines.append("=" * 65)
    lines.append("  INTER-RATER RELIABILITY ANALYSIS")
    lines.append(f"  AI Misuse Evaluator — Dissertation Chapter 3 / Appendix")
    lines.append("=" * 65)
    lines.append(f"\nRaters ({len(raters)}): {', '.join(rater_names)}")
    lines.append(f"Use cases with complete data: {len(common_cases)}/{len(RATER_CASES)}")
    lines.append("")

    for dimension in ["ethical_risk_score", "transparency_score"]:
        dim_label = "Ethical Risk" if dimension == "ethical_risk_score" else "Transparency"
        lines.append("─" * 65)
        lines.append(f"DIMENSION: {dim_label.upper()} (scale 1–5, ordinal)")
        lines.append("─" * 65)

        # Aligned score matrix: rows = raters, cols = use cases
        score_matrix = []
        for rater_name in rater_names:
            row = [raters[rater_name].get(c, {}).get(dimension) for c in common_cases]
            score_matrix.append(row)

        # Pairwise Cohen's Kappa
        lines.append("\nPairwise Linear Weighted Cohen's Kappa:")
        kappas = []
        for (i, name_a), (j, name_b) in combinations(enumerate(rater_names), 2):
            a = [v for v in score_matrix[i] if v is not None]
            b = [v for v in score_matrix[j] if v is not None]
            # Align — only cases both raters scored
            pairs = [(score_matrix[i][k], score_matrix[j][k])
                     for k in range(len(common_cases))
                     if score_matrix[i][k] is not None and score_matrix[j][k] is not None]
            if len(pairs) < 3:
                lines.append(f"  {name_a} vs {name_b}: insufficient data")
                continue
            a_vals = [p[0] for p in pairs]
            b_vals = [p[1] for p in pairs]
            kappa = weighted_cohen_kappa(a_vals, b_vals)
            kappas.append(kappa)
            lines.append(
                f"  {name_a:<25} vs {name_b:<25} "
                f"kappa = {kappa:.3f}  ({interpret_kappa(kappa)})"
            )

        if kappas:
            lines.append(f"\n  Mean kappa across all pairs: {sum(kappas)/len(kappas):.3f}")

        # Krippendorff's Alpha
        alpha = krippendorff_alpha_ordinal(score_matrix)
        lines.append(f"  Krippendorff's Alpha (ordinal, all raters): {alpha:.3f}")
        if alpha >= 0.80:
            alpha_interp = "good reliability (>= 0.80)"
        elif alpha >= 0.67:
            alpha_interp = "acceptable reliability (>= 0.67)"
        else:
            alpha_interp = "unreliable (< 0.67) — note in dissertation limitations"
        lines.append(f"  Interpretation: {alpha_interp}")
        lines.append("")

        # Exact agreement %
        exact_agreements = 0
        total_pairs_n = 0
        for pairs_idx in range(len(common_cases)):
            vals = [score_matrix[r][pairs_idx] for r in range(len(rater_names))
                    if score_matrix[r][pairs_idx] is not None]
            if len(vals) >= 2:
                for i_v in range(len(vals)):
                    for j_v in range(i_v + 1, len(vals)):
                        if vals[i_v] == vals[j_v]:
                            exact_agreements += 1
                        total_pairs_n += 1

        pct_exact = (exact_agreements / total_pairs_n * 100) if total_pairs_n > 0 else 0
        lines.append(f"  Exact agreement: {exact_agreements}/{total_pairs_n} pairs ({pct_exact:.1f}%)")

        # Mean absolute disagreement per use case
        lines.append(f"\nPer-use-case mean absolute disagreement ({dim_label}):")
        for ci, case in enumerate(common_cases):
            vals = [score_matrix[r][ci] for r in range(len(rater_names))
                    if score_matrix[r][ci] is not None]
            if len(vals) < 2:
                continue
            diffs = [abs(vals[i] - vals[j])
                     for i in range(len(vals))
                     for j in range(i + 1, len(vals))]
            mean_diff = sum(diffs) / len(diffs)
            scores_str = ", ".join(f"{name}: {score_matrix[r][ci]}"
                                   for r, name in enumerate(rater_names)
                                   if score_matrix[r][ci] is not None)
            flag = " ← HIGH DISAGREEMENT" if mean_diff >= 2.0 else ""
            lines.append(f"  {case:<45}  mean|Δ|={mean_diff:.2f}  [{scores_str}]{flag}")

        lines.append("")

    # ── Summary table for dissertation ───────────────────────────────────
    lines.append("─" * 65)
    lines.append("SUMMARY TABLE (for dissertation)")
    lines.append("─" * 65)
    lines.append(f"{'Metric':<45} {'Ethical Risk':>14} {'Transparency':>14}")
    lines.append("  " + "-" * 61)

    for dimension, label in [("ethical_risk_score", "Ethical Risk"), ("transparency_score", "Transparency")]:
        pass  # computed inline above; we'll redo quickly

    # Recompute summary values
    summary = {}
    for dimension in ["ethical_risk_score", "transparency_score"]:
        score_matrix = []
        for rater_name in rater_names:
            row = [raters[rater_name].get(c, {}).get(dimension) for c in common_cases]
            score_matrix.append(row)

        kappas = []
        for (i, _), (j, _) in combinations(enumerate(rater_names), 2):
            pairs = [(score_matrix[i][k], score_matrix[j][k])
                     for k in range(len(common_cases))
                     if score_matrix[i][k] is not None and score_matrix[j][k] is not None]
            if len(pairs) >= 3:
                kappas.append(weighted_cohen_kappa([p[0] for p in pairs], [p[1] for p in pairs]))

        alpha = krippendorff_alpha_ordinal(score_matrix)
        exact = sum(1 for ci in range(len(common_cases))
                    for i, j in combinations(range(len(rater_names)), 2)
                    if score_matrix[i][ci] is not None and score_matrix[j][ci] is not None
                    and score_matrix[i][ci] == score_matrix[j][ci])
        total_p = sum(1 for ci in range(len(common_cases))
                      for i, j in combinations(range(len(rater_names)), 2)
                      if score_matrix[i][ci] is not None and score_matrix[j][ci] is not None)

        summary[dimension] = {
            "mean_kappa": f"{sum(kappas)/len(kappas):.3f}" if kappas else "n/a",
            "alpha":      f"{alpha:.3f}",
            "exact_pct":  f"{exact/total_p*100:.1f}%" if total_p > 0 else "n/a",
        }

    eth = summary["ethical_risk_score"]
    tr  = summary["transparency_score"]
    label_kappa = "Mean pairwise Cohen's kappa (linear weighted)"
    lines.append(f"  {label_kappa:<45} {eth['mean_kappa']:>14} {tr['mean_kappa']:>14}")
    lines.append(f"  {'Krippendorff Alpha (ordinal, all raters)':<45} {eth['alpha']:>14} {tr['alpha']:>14}")
    lines.append(f"  {'Exact agreement %':<45} {eth['exact_pct']:>14} {tr['exact_pct']:>14}")
    lines.append(f"  {'n raters':<45} {len(raters):>14} {len(raters):>14}")
    lines.append(f"  {'n use cases':<45} {len(common_cases):>14} {len(common_cases):>14}")
    lines.append("")

    return "\n".join(lines)


# ════════════════════════════════════════════════════════════════════════════
# MAIN
# ════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys

    # Auto-discover rater files: data/rater_1.csv, data/rater_2.csv, …
    data_dir = "data"
    rater_files = sorted(
        [os.path.join(data_dir, f)
         for f in os.listdir(data_dir)
         if f.startswith("rater_") and f.endswith(".csv")]
    )

    if not rater_files:
        print(
            "\nNo rater CSV files found in data/.\n"
            "Expected files like:  data/rater_1.csv  data/rater_2.csv\n"
            "Each should have columns: use_case_name, ethical_risk_score, transparency_score\n"
            "(The inter_rater_scoring_sheet.html generates this format automatically.)\n"
        )
        print("Running with AUTHOR-ONLY data to show expected output format...\n")

    report = run_analysis(rater_files)
    print(report)

    # Write to file
    out_path = os.path.join(data_dir, "inter_rater_results.txt")
    os.makedirs(data_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n✅ Report saved to {out_path}")